name: Test and Build Kibana Reports

on: [pull_request, push]

env:
  PLUGIN_NAME: opendistroReportsKibana
  OD_VERSION: 1.12.0.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Plugin
        uses: actions/checkout@v1

      - name: Checkout Kibana
        uses: actions/checkout@v1
        with:
          repository: elastic/kibana
          ref: v7.10.0
          path: kibana-reports/kibana

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "10.22.1"

      - name: Move Kibana Reports to Plugins Dir
        run: mv kibana-reports kibana/plugins

      - name: Kibana Plugin Bootstrap
        uses: nick-invision/retry@v1
        with:
          timeout_minutes: 30
          max_attempts: 3
          command: cd kibana/plugins/kibana-reports; yarn kbn bootstrap

      # - name: Test
      #   uses: nick-invision/retry@v1
      #   with:
      #     timeout_minutes: 30
      #     max_attempts: 3
      #     command: cd kibana/plugins/kibana-reports; yarn test

      - name: Build Artifact
        run: |
          cd kibana/plugins/kibana-reports
          yarn build
          cd build
          mkdir -p ./{ubuntu,centos,al2,windows}/kibana/opendistroKibanaReports
          cp ./opendistro*-*.zip ./ubuntu/${{ env.PLUGIN_NAME }}-${{ env.OD_VERSION }}-ubuntu-x64.zip
          cp ./opendistro*-*.zip ./centos/${{ env.PLUGIN_NAME }}-${{ env.OD_VERSION }}-centos-x64.zip
          cp ./opendistro*-*.zip ./al2/${{ env.PLUGIN_NAME }}-${{ env.OD_VERSION }}-al2-x64.zip
          cp ./opendistro*-*.zip ./windows/${{ env.PLUGIN_NAME }}-${{ env.OD_VERSION }}-windows-x64.zip
          cd al2
          wget https://github.com/opendistro-for-elasticsearch/kibana-reports/releases/download/chromium-1.12.0.0/chromium-al2.zip
          unzip chromium-al2.zip -d ./kibana/opendistroKibanaReports
          zip -r ./${{ env.PLUGIN_NAME }}-*.zip ./kibana

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: kibana-reports
          path: |
            kibana/plugins/kibana-reports/build/ubuntu
            kibana/plugins/kibana-reports/build/al2
            kibana/plugins/kibana-reports/build/centos
            kibana/plugins/kibana-reports/build/windows
